[workspace]
members = [
    "examples/as_string",
    "examples/backwards_compat",
    "examples/json",
    "examples/opcode",
    "rkyv*",
]
default-members = [
    "rkyv",
    "rkyv_dyn",
    "rkyv_dyn_test",
    "rkyv_test",
    "rkyv_typename",
]

[workspace.package]
version = "0.7.43"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/rkyv/rkyv"

[workspace.dependencies]
bytecheck = { version = "=0.6.11", default-features = false }
proc-macro2 = "1.0"
ptr_meta = { version = "~0.1.3", default-features = false }
quote = "1.0"
syn = "1.0"
wasm-bindgen-test = "0.3"
